openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Ambulance Waiting List management for Web-In-Cloud system
  version: "1.0.0"
  title: Waiting List Api
  contact:
    email: xlednickym@stuba.sk
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
 - name: ledTreatmentList
   description: Treatment List API
paths:
 "/treatments":
   get:
     tags:
       - ledTreatmentList
     summary: Provides the list of all treatments
     operationId: getTreatments
     description: Get list of treatments
     responses:
       "200":
         description: treatments list
         content:
           application/json:
             schema:
               type: array
               items:
                 $ref: "#/components/schemas/Treatment"
             examples:
               response:
                 $ref: "#/components/examples/TreatmentsExample"
components:
 schemas:
   Treatment:
     type: object
     required: [id, patientId]
     properties:
       id:
         type: string
         example: x321ab3
         description: Unique id of treatment
       name:
         type: string
         example: Jožko Púčik
         description: Name of patient
       patientId:
         type: string
         example: 460527-jozef-pucik
         description: Unique identifier of the patient known to Web-In-Cloud system
       startDate:
         type: string
         format: date-time
         example: "2038-12-24T10:05:00Z"
         description: Timestamp when the treatment started
       endDate:
         type: string
         format: date-time
         example: "2038-12-24T10:35:00Z"
         description: Timestamp when the treatment will end
 examples:
    TreatmentsExample:
      summary: List of treatments
      description: |
        Example treatments list containing 3 treatments
      value:
      - id: x321ab3
        name: Jožko Púčik
        patientId: 460527-jozef-pucik
        startDate: "2024-01-01T10:05:00.000Z"
        endDate: "2024-06-01T10:35:00.000Z"
      - id: x321ab4
        name: Ferdinand Trety
        patientId: 780907-ferdinand-tre
        startDate: "2024-02-01T10:25:00.000Z"
        endDate: "2024-08-10T10:50:00.000Z"
      - id: x321ab5
        name: Janko Hraško
        patientId: 230101-janko-hrasko
        startDate: "2024-05-15T09:00:00.000Z"
        endDate: "2024-12-24T10:15:00.000Z"